version: 2

updates:
  - package-ecosystem: 'yarn'
    directory: '/bot'
    schedule:
      interval: 'weekly'

updates:
  - package-ecosystem: 'cargo'
    directory: '/api'
    schedule:
      interval: 'weekly'