version: "3.9"
services:
  api:
    build: ./api
    image: sirh/c2s:api
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  bot:
    build: ./bot
    image: sirh/c2s:semblance
    environment:
      - NODE_ENV=production
    container_name: bot
    restart: unless-stopped
    ports:
      - "8008:8008"
    stdin_open: true
    tty: true
  botlist:
    build: ./botlist
    image: sirh/c2s:botlist
    environment:
      - NODE_ENV=production
    container_name: botlist
    restart: unless-stopped
    ports:
      - "8079:8079"
    stdin_open: true
    tty: true
  twitter:
    build: ./twitter
    image: sirh/c2s:twitter
    environment:
      - NODE_ENV=production
    container_name: twitter
    restart: unless-stopped
    stdin_open: true
    tty: true
