"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StickerPacks = exports.Sticker = exports.Semblance = exports.dblSDK = exports.bfdSDK = exports.blsSDK = exports.dboatsSDK = void 0;
exports.blsSDK = require("./@botlist-space/sdk");
exports.bfdSDK = require("./@bots-for-discord/sdk");
exports.dblSDK = require("./@discord-bot-list/sdk");
exports.dboatsSDK = require('./@discord-boats/sdk');
var Semblance_1 = require("./Semblance");
Object.defineProperty(exports, "Semblance", { enumerable: true, get: function () { return Semblance_1.Semblance; } });
var Sticker_1 = require("./Sticker");
Object.defineProperty(exports, "Sticker", { enumerable: true, get: function () { return Sticker_1.Sticker; } });
var StickerPacks_1 = require("./StickerPacks");
Object.defineProperty(exports, "StickerPacks", { enumerable: true, get: function () { return StickerPacks_1.StickerPacks; } });
